meta_product_name: "Front Row"
meta_title: "Front Row - Live From Your Living Room"
meta_description: "Live stream music platform"
meta_image: "Cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
